# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonemanufac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phonemodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonmode', models.CharField(max_length=50)),
                ('manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.phonemanufac')),
            ],
        ),
    ]
