# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_phonemanufac_phonemodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phonemodels',
            new_name='phonemode',
        ),
    ]
