# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20160419_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phonemanufac',
            new_name='phonemanufac1',
        ),
        migrations.RenameModel(
            old_name='phonemode',
            new_name='phonemode1',
        ),
    ]
