# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20160419_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='phm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonmode', models.CharField(max_length=50)),
                ('manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.ph')),
            ],
        ),
        migrations.RemoveField(
            model_name='phonemode1',
            name='manu',
        ),
        migrations.DeleteModel(
            name='phonemanufac1',
        ),
        migrations.DeleteModel(
            name='phonemode1',
        ),
    ]
